# Generated by Django 3.0.4 on 2020-03-26 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainpage', '0005_auto_20200322_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('institution_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.Edition')),
            ],
        ),
    ]
