# Generated by Django 3.0.4 on 2020-03-26 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedu_tutor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('institution', models.ManyToManyField(to='speedu_tutor.Institution')),
            ],
        ),
    ]
