# Generated by Django 3.0.4 on 2020-03-26 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speedu_tutor', '0002_career'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miercoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sabado')], max_length=10)),
                ('hour_start', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('semester', models.IntegerField()),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speedu_tutor.Career')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('career', models.ManyToManyField(to='speedu_tutor.Career')),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('state', models.CharField(choices=[('0', 'Programada'), ('1', 'Termininada')], default='Programada', max_length=1)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speedu_tutor.Schedule')),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('argument', models.TextField()),
                ('state', models.CharField(choices=[('V', 'En Verificación'), ('A', 'Aprobado'), ('R', 'Rechsazado'), ('I', 'Inactivo')], default='En Verificación', max_length=1)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='speedu_tutor.Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speedu_tutor.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speedu_tutor.Tutor'),
        ),
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended_tutor', models.BooleanField()),
                ('attended_student', models.BooleanField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speedu_tutor.Student')),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speedu_tutor.Tutorial')),
            ],
        ),
    ]
