# Generated by Django 3.0.4 on 2020-04-21 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedu_tutor', '0008_auto_20200421_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='telefono',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
