# Generated by Django 3.0.4 on 2020-04-23 01:55

from django.db import migrations, models
import speedu_tutor.models


class Migration(migrations.Migration):

    dependencies = [
        ('speedu_tutor', '0009_auto_20200421_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='image',
            field=models.ImageField(default='asdasd.png', upload_to=speedu_tutor.models.wrapper),
            preserve_default=False,
        ),
    ]
