# Generated by Django 3.0.4 on 2020-04-23 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speedu_tutor', '0010_institution_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='speedu_tutor.Institution'),
            preserve_default=False,
        ),
    ]
