# Generated by Django 3.0.4 on 2020-03-16 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_auto_20200315_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configmainpagemodel',
            name='logo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
