# Generated by Django 3.0.4 on 2020-03-22 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_edition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(help_text='Nombre de la institución', max_length=255)),
                ('name', models.CharField(help_text='Nombres del representante', max_length=100)),
                ('lastname', models.CharField(help_text='Apellidos del representante', max_length=100)),
                ('email', models.CharField(help_text='Correo de contacto', max_length=100)),
                ('phone', models.IntegerField(help_text='Teléfono de contacto')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.City')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.Edition')),
            ],
        ),
    ]
