# Generated by Django 3.0.3 on 2020-03-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_auto_20200315_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigMainPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(help_text='Logotipo de la página', upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='ConfigMainPageModel',
        ),
    ]
