# Generated by Django 3.0.4 on 2020-03-22 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_registers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registers',
            new_name='Register',
        ),
    ]
