# Generated by Django 3.0.4 on 2020-03-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_auto_20200316_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='configmainpage',
            name='title',
            field=models.CharField(default='SpeedU', help_text='Título de la página', max_length=30),
        ),
    ]
