# Generated by Django 3.0.4 on 2020-03-19 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_configmainpage_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfigMainPage',
        ),
    ]
