# Generated by Django 3.0.4 on 2020-04-08 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speedu_tutor', '0005_remove_institution_institution_type'),
        ('mainpage', '0005_auto_20200322_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='edition',
        ),
        migrations.DeleteModel(
            name='Edition',
        ),
    ]
